### ISSUE TITLE
Cant build on Xcode 6.4

### ISSUE THREAD

**Issue by moh1122** [MoZhouqi/PhotoBrowser#2]
Hello
Thanks for this great project but its giving some errors while building it:
# import "FastImageCache/FICImageTable.h" not found

can you help me in this 
thank you

**Comment by MoZhouqi** [comment]
Could you try to open PhotoBrowser.xcworkspace?

**Comment by MoZhouqi** [comment]
I will close the issue, If you have any questions, please don't hesitate to reopen it.
