### ISSUE TITLE
"http://api.instagram.com/oauth/authorize/%3Fclient_id=dbdedf9dcff441789aff45fbbbde2a27&redirect_uri=http://www.qushang.net/&response_type=code"

### ISSUE THREAD

**Issue by patrickpeng2091** [MoZhouqi/PhotoBrowser#3]
My  CLIENT INFO
CLIENT ID   dbdedf9dcff441789aff45fbbbde2a27
CLIENT SECRET   cbf05e7e69104266be719972c841bbca
WEBSITE URL http://www.qushang.net/
REDIRECT URI    http://www.qushang.net
SUPPORT EMAIL   mlonet@hotmail.com

run success 

show message
"http://api.instagram.com/oauth/authorize/%3Fclient_id=dbdedf9dcff441789aff45fbbbde2a27&redirect_uri=http://www.qushang.net/&response_type=code"

**Comment by MoZhouqi** [comment]
Hi, the url should be "https://api.instagram.com/oauth/authorize/%3Fclient_id=dbdedf9dcff441789aff45fbbbde2a27&redirect_uri=http://www.qushang.net&response_type=code", the value of  `redirect_uri` parameter is `http://www.qushang.net`, it is not a slash at the end.

**Comment by patrickpeng2091** [comment]
Use http://www.qushang.net 

Display
"https://api.instagram.com/oauth/authorize/%3Fclient_id=dbdedf9dcff441789aff45fbbbde2a27&redirect_uri=http://www.qushang.net&response_type=code"

**Comment by MoZhouqi** [comment]
Is the user interface is blank?

**Comment by patrickpeng2091** [comment]
![21](https://cloud.githubusercontent.com/assets/4326820/10967477/ee3539b0-83f5-11e5-8e57-5b87391bc44b.png)

**Comment by MoZhouqi** [comment]
Instagram is blocked by the GFW, so you need to break through the wall.
