### ISSUE TITLE
Can't display images in uicollectionview while running on iPad

### ISSUE THREAD

**Issue by sagar-vaholiya** [MoZhouqi/PhotoBrowser#4]
Your example made for iPhone. But, I make this for Universal and When i run this app on iPad, UICollectionview doesn't shows images in cell. In log, one warning occurred  in Log, i.e. 

"[/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI_Sim/CoreUI-371.4/Bom/Storage/BOMStorage.c:522] <memory> is not a BOMStorage file"

Please help me out from this.
I have Xcode 7.2 and Deployment target for app is 9.2.

![screen shot 2016-01-06 at 11 54 46 am](https://cloud.githubusercontent.com/assets/10954272/12136298/54797050-b46c-11e5-8b91-1348c1bf297a.png)

**Comment by MoZhouqi** [comment]
Added iPad support in eb6b7610cd805031d0e198a334a9ce4625b77ddb. Thanks for the feedback, @sagar-vaholiya!
