### ISSUE TITLE
How to use scopes in URL?

### ISSUE THREAD

**Issue by sagar-vaholiya** [MoZhouqi/PhotoBrowser#5]
i got "**basic**" scope permission. As per new permission review [(changelog),](https://www.instagram.com/developer/changelog/)
 And i have to use this scope in url as,

var URLRequest: NSMutableURLRequest {
            let result: (path: String, parameters: [String: AnyObject]?) = {
                switch self {
                case .PopularPhotos (let userID, let accessToken):
                    let params = ["access_token": accessToken]
                    let pathString = "/v1/users/self/feed"
                    return (pathString, params)

```
            case .requestOauthCode:
                let pathString = "/oauth/authorize/?client_id=" + Router.clientID + "&redirect_uri=" + Router.redirectURI + "&response_type=code&scope=basic"
                return (pathString, nil)
            }
            }()

        let BaeseURL = NSURL(string: Router.baseURLString)!
        let URLRequest = NSURLRequest(URL: BaeseURL.URLByAppendingPathComponent(result.path))
        let encoding = Alamofire.ParameterEncoding.URL
        return encoding.encode(URLRequest, parameters: result.parameters).0
    }
}
```

In **pathString** variable, i **store scope at last**.
i used as above but data reruns **nil**..

Is it right way to use scope?

**Comment by MoZhouqi** [comment]
Yes, it is right.  Do you receive any error message?

**Comment by sagar-vaholiya** [comment]
No, i didn't get any kind of error message. but data which i got in response returning nil.

and if i don't use scope "&scope=basic" in pathString then it works.

so, i confused that, should i use "basic" scope or not?

**Comment by MoZhouqi** [comment]
Which request returns a nil response object?

I try to use my client info and add the scope parameter to the authorization request then it works.

**Comment by sagar-vaholiya** [comment]
try another username or password which not connected to your client info.

**Comment by sagar-vaholiya** [comment]
i think i need any other scope for that, am i right?

**Comment by MoZhouqi** [comment]
Yes, I have revoked the access and then re-authorized.

I just use the "basic" scope.
