### ISSUE TITLE
 API error

### ISSUE THREAD

**Issue by tysun** [MoZhouqi/PhotoBrowser#7]
Hi Mo

I was wondering if you're Instagram.swift file is up to date? 

I put in my Instagram ClientID and Secret, but I have an API error. 
`https://api.instagram.com/oauth/authorize/%3Fclient_id=d9e82bcb24414e539480724305f3f004&redirect_uri=http://localhost&response_type=code"` [I used a fake ClientID for this message]

I am using your code to learn about the Instagram API and I think maybe something needs updating?

Thank you for sharing your project. 

<img width="374" alt="screen shot 2016-07-13 at 18 19 46" src="https://cloud.githubusercontent.com/assets/11150198/16825089/6e206352-4926-11e6-8be5-24629a7df077.png">

**Comment by MoZhouqi** [comment]
Fixed in 3d9768e4c1dca42f0b52ed3d4221d7afe2f6c91d.
